# Generated by Django 4.0.3 on 2022-03-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='study_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
