# Generated by Django 3.2.12 on 2022-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_data', models.TextField()),
                ('face_x_mean', models.FloatField(default=0.0)),
                ('face_y_mean', models.FloatField(default=0.0)),
                ('nose_mean', models.FloatField(default=0.0)),
                ('face_x', models.TextField(blank=True, default=None, null=True)),
                ('face_y', models.TextField(blank=True, default=None, null=True)),
                ('nose_to_center', models.TextField(blank=True, default=None, null=True)),
                ('cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
