# Generated by Django 4.0.3 on 2022-03-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='face',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='detection',
            name='nose_to_center',
            field=models.TextField(default=None),
        ),
    ]
