# Generated by Django 3.2.12 on 2022-03-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='blob_data',
            field=models.BinaryField(),
        ),
    ]
