# Generated by Django 3.2.12 on 2022-03-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_alter_detection_blob_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='blob_data',
            field=models.FileField(upload_to=''),
        ),
    ]
