# Generated by Django 4.0.3 on 2022-03-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_detection_cnt_detection_face_mean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='face',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='nose_to_center',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
