# Generated by Django 3.2.12 on 2022-03-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0004_alter_detection_blob_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='blob_data',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
