# Generated by Django 3.2.12 on 2022-04-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0008_auto_20220401_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='blinkdetection',
            name='detection_flag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='neckdetection',
            name='detection_flag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
