# Generated by Django 3.1.12 on 2022-04-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongos', '0002_rename_base64_mongo_base642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mongo',
            old_name='base642',
            new_name='blob_base64',
        ),
        migrations.RemoveField(
            model_name='mongo',
            name='test_cnt',
        ),
    ]
